name: "CD"

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

defaults:
  run:
    shell: sh

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ SECRETS.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ SECRETS.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set-Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
          cache: yarn
          cache-dependency-path: ./frontend/yarn.lock
      - name: Install Vercel CLI
        run: |
          cd frontend
          yarn global add vercel@latest
      - name: Pull Vercel Environment Information
        run: |
          cd frontend
          vercel pull --yes --environment production --token ${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: |
          cd frontend
          vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          cd frontend
          vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
