name: "MR Pipeline"

on:
  pull_request:

defaults:
  run:
    shell: sh

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set-Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
          cache: yarn
          cache-dependency-path: ./frontend/yarn.lock
      - name: Install dependencies
        run: |
          cd frontend
          yarn install
      - name: Run linting
        run: |
          cd frontend
          yarn lint
      - name: Run formatting
        run: |
          cd frontend
          yarn format --check
  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set-Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
          cache: yarn
          cache-dependency-path: ./frontend/yarn.lock
      - name: Install dependencies
        run: |
          cd frontend
          yarn install
      - name: Build
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
        run: |
          cd frontend
          yarn build
  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set-Up Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.14.0
  #         cache: yarn
  #         cache-dependency-path: ./frontend/yarn.lock
  #     - name: Deploy to preview
  #       working-directory: ./frontend
  #       uses: amondnet/vercel-action@v25.2.0
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
